-- 코드를 입력하세요
WITH BT AS (
SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE, B.PUBLISHED_DATE, A.AUTHOR_NAME
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
)

SELECT BT.AUTHOR_ID, BT.AUTHOR_NAME, BT.CATEGORY, SUM(BT.PRICE*BI.SALES) TOTAL_SALES
FROM BOOK_SALES BI LEFT JOIN BT ON BI.BOOK_ID = BT.BOOK_ID
WHERE YEAR(BI.SALES_DATE) = 2022 AND MONTH(BI.SALES_DATE) = 1
GROUP BY BT.CATEGORY, BT.AUTHOR_ID
ORDER BY BT.AUTHOR_ID ASC, BT.CATEGORY DESC