-- 코드를 입력하세요
SELECT RES.REST_ID, RES.REST_NAME, RES.FOOD_TYPE, RES.FAVORITES, RES.ADDRESS, ROUND(AVG(REV.REVIEW_SCORE), 2) SCORE
FROM REST_INFO AS RES JOIN REST_REVIEW AS REV ON RES.REST_ID = REV.REST_ID
WHERE RES.ADDRESS LIKE '서울%'
GROUP BY RES.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC
# SELECT *
# FROM REST_INFO AS RES JOIN REST_REVIEW AS REV ON RES.REST_ID = REV.REST_ID
