-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UB JOIN USED_GOODS_USER UU ON UB.WRITER_ID = UU.USER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY UU.USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES
